import { defineConfig } from "vite";
import { resolve } from "path";
import tailwindcss from "@tailwindcss/vite";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  plugins: [
    tailwindcss(),
    VitePWA({
      registerType: "autoUpdate",
      strategies: "generateSW",
      workbox: {
        // Offline-first (018): precache the full app shell — all HTML pages,
        // bundles, styles, and icons. login.html must render offline so an
        // expired-marker redirect still lands somewhere usable.
        globPatterns: ["**/*.{js,css,html,png,svg,ico,webmanifest,woff2}"],
        // API navigations must never fall back to cached HTML.
        navigateFallbackDenylist: [/^\/api\//],
        runtimeCaching: [
          {
            // config.json is generated by entrypoint.sh at container start, so
            // it cannot be precached at build time. Network-first keeps it
            // fresh; the cached copy serves offline. /api/* deliberately has
            // no runtime route — data requests always hit the network.
            urlPattern: /\/config\.json$/,
            handler: "NetworkFirst",
            options: { cacheName: "config" },
          },
        ],
      },
      manifest: {
        name: "Weight Tracker",
        short_name: "WeightTracker",
        start_url: "/",
        scope: "/",
        display: "standalone",
        theme_color: "#4f46e5",
        background_color: "#ffffff",
        icons: [
          {
            src: "/icons/icon-192.png",
            sizes: "192x192",
            type: "image/png",
          },
          {
            src: "/icons/icon-512.png",
            sizes: "512x512",
            type: "image/png",
          },
        ],
      },
    }),
  ],
  root: "src",
  publicDir: "../public",
  build: {
    outDir: "../dist",
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, "src/index.html"),
        login: resolve(__dirname, "src/login.html"),
        setup: resolve(__dirname, "src/setup.html"),
        resetRequest: resolve(__dirname, "src/reset-request.html"),
        resetComplete: resolve(__dirname, "src/reset-complete.html"),
        confirmEmail: resolve(__dirname, "src/confirm-email.html"),
        profile: resolve(__dirname, "src/profile.html"),
        admin: resolve(__dirname, "src/admin.html"),
      },
    },
  },
});
